// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: contracts/wsMessages/models.proto

package wsMessages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParticipantStatus int32

const (
	ParticipantStatus_Active ParticipantStatus = 0
	ParticipantStatus_Banned ParticipantStatus = 1
)

// Enum value maps for ParticipantStatus.
var (
	ParticipantStatus_name = map[int32]string{
		0: "Active",
		1: "Banned",
	}
	ParticipantStatus_value = map[string]int32{
		"Active": 0,
		"Banned": 1,
	}
)

func (x ParticipantStatus) Enum() *ParticipantStatus {
	p := new(ParticipantStatus)
	*p = x
	return p
}

func (x ParticipantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParticipantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_wsMessages_models_proto_enumTypes[0].Descriptor()
}

func (ParticipantStatus) Type() protoreflect.EnumType {
	return &file_contracts_wsMessages_models_proto_enumTypes[0]
}

func (x ParticipantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParticipantStatus.Descriptor instead.
func (ParticipantStatus) EnumDescriptor() ([]byte, []int) {
	return file_contracts_wsMessages_models_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_ParticipantCreated MessageType = 0
	MessageType_System             MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "ParticipantCreated",
		1: "System",
	}
	MessageType_value = map[string]int32{
		"ParticipantCreated": 0,
		"System":             1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_wsMessages_models_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_contracts_wsMessages_models_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_contracts_wsMessages_models_proto_rawDescGZIP(), []int{1}
}

type MessageSubType int32

const (
	MessageSubType_ParticipantJoined MessageSubType = 0
	MessageSubType_ChatCreated       MessageSubType = 1
	MessageSubType_TextMessage       MessageSubType = 2
)

// Enum value maps for MessageSubType.
var (
	MessageSubType_name = map[int32]string{
		0: "ParticipantJoined",
		1: "ChatCreated",
		2: "TextMessage",
	}
	MessageSubType_value = map[string]int32{
		"ParticipantJoined": 0,
		"ChatCreated":       1,
		"TextMessage":       2,
	}
)

func (x MessageSubType) Enum() *MessageSubType {
	p := new(MessageSubType)
	*p = x
	return p
}

func (x MessageSubType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageSubType) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_wsMessages_models_proto_enumTypes[2].Descriptor()
}

func (MessageSubType) Type() protoreflect.EnumType {
	return &file_contracts_wsMessages_models_proto_enumTypes[2]
}

func (x MessageSubType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageSubType.Descriptor instead.
func (MessageSubType) EnumDescriptor() ([]byte, []int) {
	return file_contracts_wsMessages_models_proto_rawDescGZIP(), []int{2}
}

type WSRoomTypes int32

const (
	WSRoomTypes_Channel     WSRoomTypes = 0
	WSRoomTypes_Participant WSRoomTypes = 1
)

// Enum value maps for WSRoomTypes.
var (
	WSRoomTypes_name = map[int32]string{
		0: "Channel",
		1: "Participant",
	}
	WSRoomTypes_value = map[string]int32{
		"Channel":     0,
		"Participant": 1,
	}
)

func (x WSRoomTypes) Enum() *WSRoomTypes {
	p := new(WSRoomTypes)
	*p = x
	return p
}

func (x WSRoomTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WSRoomTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_wsMessages_models_proto_enumTypes[3].Descriptor()
}

func (WSRoomTypes) Type() protoreflect.EnumType {
	return &file_contracts_wsMessages_models_proto_enumTypes[3]
}

func (x WSRoomTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WSRoomTypes.Descriptor instead.
func (WSRoomTypes) EnumDescriptor() ([]byte, []int) {
	return file_contracts_wsMessages_models_proto_rawDescGZIP(), []int{3}
}

type ParticipantShortInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	LastSeenAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=lastSeenAt,proto3" json:"lastSeenAt,omitempty"`
	IsOnline   bool                   `protobuf:"varint,3,opt,name=isOnline,proto3" json:"isOnline,omitempty"`
	CustomData *CustomData            `protobuf:"bytes,4,opt,name=customData,proto3,oneof" json:"customData,omitempty"`
}

func (x *ParticipantShortInfo) Reset() {
	*x = ParticipantShortInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_wsMessages_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParticipantShortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantShortInfo) ProtoMessage() {}

func (x *ParticipantShortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_wsMessages_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantShortInfo.ProtoReflect.Descriptor instead.
func (*ParticipantShortInfo) Descriptor() ([]byte, []int) {
	return file_contracts_wsMessages_models_proto_rawDescGZIP(), []int{0}
}

func (x *ParticipantShortInfo) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ParticipantShortInfo) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *ParticipantShortInfo) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *ParticipantShortInfo) GetCustomData() *CustomData {
	if x != nil {
		return x.CustomData
	}
	return nil
}

type ChannelParticipantGrants struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendMessage  *bool `protobuf:"varint,1,opt,name=sendMessage,proto3,oneof" json:"sendMessage,omitempty"`
	ReadMessages *bool `protobuf:"varint,2,opt,name=readMessages,proto3,oneof" json:"readMessages,omitempty"`
	Admin        *bool `protobuf:"varint,3,opt,name=admin,proto3,oneof" json:"admin,omitempty"`
}

func (x *ChannelParticipantGrants) Reset() {
	*x = ChannelParticipantGrants{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_wsMessages_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelParticipantGrants) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelParticipantGrants) ProtoMessage() {}

func (x *ChannelParticipantGrants) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_wsMessages_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelParticipantGrants.ProtoReflect.Descriptor instead.
func (*ChannelParticipantGrants) Descriptor() ([]byte, []int) {
	return file_contracts_wsMessages_models_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelParticipantGrants) GetSendMessage() bool {
	if x != nil && x.SendMessage != nil {
		return *x.SendMessage
	}
	return false
}

func (x *ChannelParticipantGrants) GetReadMessages() bool {
	if x != nil && x.ReadMessages != nil {
		return *x.ReadMessages
	}
	return false
}

func (x *ChannelParticipantGrants) GetAdmin() bool {
	if x != nil && x.Admin != nil {
		return *x.Admin
	}
	return false
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender            *ParticipantShortInfo  `protobuf:"bytes,2,opt,name=sender,proto3,oneof" json:"sender,omitempty"`
	Text              string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	ChannelIdentifier string                 `protobuf:"bytes,4,opt,name=channelIdentifier,proto3" json:"channelIdentifier,omitempty"`
	Type              MessageType            `protobuf:"varint,5,opt,name=type,proto3,enum=wsMessages.MessageType" json:"type,omitempty"`
	SubType           MessageSubType         `protobuf:"varint,6,opt,name=subType,proto3,enum=wsMessages.MessageSubType" json:"subType,omitempty"`
	LocalId           string                 `protobuf:"bytes,7,opt,name=localId,proto3" json:"localId,omitempty"`
	CustomData        *CustomData            `protobuf:"bytes,8,opt,name=customData,proto3,oneof" json:"customData,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_wsMessages_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_wsMessages_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_contracts_wsMessages_models_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSender() *ParticipantShortInfo {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetChannelIdentifier() string {
	if x != nil {
		return x.ChannelIdentifier
	}
	return ""
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_ParticipantCreated
}

func (x *Message) GetSubType() MessageSubType {
	if x != nil {
		return x.SubType
	}
	return MessageSubType_ParticipantJoined
}

func (x *Message) GetLocalId() string {
	if x != nil {
		return x.LocalId
	}
	return ""
}

func (x *Message) GetCustomData() *CustomData {
	if x != nil {
		return x.CustomData
	}
	return nil
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CustomEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType       WSRoomTypes `protobuf:"varint,1,opt,name=roomType,proto3,enum=wsMessages.WSRoomTypes" json:"roomType,omitempty"`
	RoomIdentifier string      `protobuf:"bytes,2,opt,name=roomIdentifier,proto3" json:"roomIdentifier,omitempty"`
	EventName      string      `protobuf:"bytes,3,opt,name=eventName,proto3" json:"eventName,omitempty"`
	CustomData     *CustomData `protobuf:"bytes,4,opt,name=customData,proto3,oneof" json:"customData,omitempty"`
}

func (x *CustomEvent) Reset() {
	*x = CustomEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_wsMessages_models_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomEvent) ProtoMessage() {}

func (x *CustomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_wsMessages_models_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomEvent.ProtoReflect.Descriptor instead.
func (*CustomEvent) Descriptor() ([]byte, []int) {
	return file_contracts_wsMessages_models_proto_rawDescGZIP(), []int{3}
}

func (x *CustomEvent) GetRoomType() WSRoomTypes {
	if x != nil {
		return x.RoomType
	}
	return WSRoomTypes_Channel
}

func (x *CustomEvent) GetRoomIdentifier() string {
	if x != nil {
		return x.RoomIdentifier
	}
	return ""
}

func (x *CustomEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *CustomEvent) GetCustomData() *CustomData {
	if x != nil {
		return x.CustomData
	}
	return nil
}

type CustomData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CustomData) Reset() {
	*x = CustomData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_wsMessages_models_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomData) ProtoMessage() {}

func (x *CustomData) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_wsMessages_models_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomData.ProtoReflect.Descriptor instead.
func (*CustomData) Descriptor() ([]byte, []int) {
	return file_contracts_wsMessages_models_proto_rawDescGZIP(), []int{4}
}

func (x *CustomData) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShortChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Identifier string      `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	CustomData *CustomData `protobuf:"bytes,4,opt,name=customData,proto3,oneof" json:"customData,omitempty"`
}

func (x *ShortChannel) Reset() {
	*x = ShortChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_wsMessages_models_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortChannel) ProtoMessage() {}

func (x *ShortChannel) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_wsMessages_models_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortChannel.ProtoReflect.Descriptor instead.
func (*ShortChannel) Descriptor() ([]byte, []int) {
	return file_contracts_wsMessages_models_proto_rawDescGZIP(), []int{5}
}

func (x *ShortChannel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShortChannel) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ShortChannel) GetCustomData() *CustomData {
	if x != nil {
		return x.CustomData
	}
	return nil
}

var File_contracts_wsMessages_models_proto protoreflect.FileDescriptor

var file_contracts_wsMessages_models_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x77, 0x73, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xda, 0x01, 0x0a, 0x14, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0a, 0x6c, 0x61, 0x73,
	0x74, 0x53, 0x65, 0x65, 0x6e, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x53,
	0x65, 0x65, 0x6e, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x0d,
	0x0a, 0x0b, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x22, 0xb0, 0x01,
	0x0a, 0x18, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69,
	0x70, 0x61, 0x6e, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x0b, 0x73, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x27, 0x0a, 0x0c, 0x72, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x0c, 0x72, 0x65, 0x61, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x05, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x22, 0xa8, 0x03, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3d, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x77,
	0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x69, 0x70, 0x61, 0x6e, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x2c, 0x0a, 0x11, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x2b, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x77, 0x73,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x73, 0x75,
	0x62, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x77, 0x73,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x73, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x0a, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x48, 0x01, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x0d, 0x0a, 0x0b,
	0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x22, 0xd4, 0x01, 0x0a, 0x0b,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x08, 0x72,
	0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e,
	0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x57, 0x53, 0x52, 0x6f, 0x6f,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x77, 0x73, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x7b, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x8a, 0x01, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x12, 0x3b, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0a,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a,
	0x0b, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x2b, 0x0a, 0x11,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x10, 0x01, 0x2a, 0x31, 0x0a, 0x0b, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10, 0x01, 0x2a, 0x49, 0x0a, 0x0e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15,
	0x0a, 0x11, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x4a, 0x6f, 0x69,
	0x6e, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x02, 0x2a, 0x2b, 0x0a, 0x0b, 0x57, 0x53, 0x52, 0x6f, 0x6f,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x6e, 0x74, 0x10, 0x01, 0x42, 0x16, 0x5a, 0x14, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x73, 0x2f, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contracts_wsMessages_models_proto_rawDescOnce sync.Once
	file_contracts_wsMessages_models_proto_rawDescData = file_contracts_wsMessages_models_proto_rawDesc
)

func file_contracts_wsMessages_models_proto_rawDescGZIP() []byte {
	file_contracts_wsMessages_models_proto_rawDescOnce.Do(func() {
		file_contracts_wsMessages_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_contracts_wsMessages_models_proto_rawDescData)
	})
	return file_contracts_wsMessages_models_proto_rawDescData
}

var file_contracts_wsMessages_models_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_contracts_wsMessages_models_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_contracts_wsMessages_models_proto_goTypes = []interface{}{
	(ParticipantStatus)(0),           // 0: wsMessages.ParticipantStatus
	(MessageType)(0),                 // 1: wsMessages.MessageType
	(MessageSubType)(0),              // 2: wsMessages.MessageSubType
	(WSRoomTypes)(0),                 // 3: wsMessages.WSRoomTypes
	(*ParticipantShortInfo)(nil),     // 4: wsMessages.ParticipantShortInfo
	(*ChannelParticipantGrants)(nil), // 5: wsMessages.ChannelParticipantGrants
	(*Message)(nil),                  // 6: wsMessages.Message
	(*CustomEvent)(nil),              // 7: wsMessages.CustomEvent
	(*CustomData)(nil),               // 8: wsMessages.CustomData
	(*ShortChannel)(nil),             // 9: wsMessages.ShortChannel
	nil,                              // 10: wsMessages.CustomData.DataEntry
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_contracts_wsMessages_models_proto_depIdxs = []int32{
	11, // 0: wsMessages.ParticipantShortInfo.lastSeenAt:type_name -> google.protobuf.Timestamp
	8,  // 1: wsMessages.ParticipantShortInfo.customData:type_name -> wsMessages.CustomData
	4,  // 2: wsMessages.Message.sender:type_name -> wsMessages.ParticipantShortInfo
	1,  // 3: wsMessages.Message.type:type_name -> wsMessages.MessageType
	2,  // 4: wsMessages.Message.subType:type_name -> wsMessages.MessageSubType
	8,  // 5: wsMessages.Message.customData:type_name -> wsMessages.CustomData
	11, // 6: wsMessages.Message.createdAt:type_name -> google.protobuf.Timestamp
	3,  // 7: wsMessages.CustomEvent.roomType:type_name -> wsMessages.WSRoomTypes
	8,  // 8: wsMessages.CustomEvent.customData:type_name -> wsMessages.CustomData
	10, // 9: wsMessages.CustomData.data:type_name -> wsMessages.CustomData.DataEntry
	8,  // 10: wsMessages.ShortChannel.customData:type_name -> wsMessages.CustomData
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_contracts_wsMessages_models_proto_init() }
func file_contracts_wsMessages_models_proto_init() {
	if File_contracts_wsMessages_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contracts_wsMessages_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParticipantShortInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contracts_wsMessages_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelParticipantGrants); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contracts_wsMessages_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contracts_wsMessages_models_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contracts_wsMessages_models_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contracts_wsMessages_models_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_contracts_wsMessages_models_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_contracts_wsMessages_models_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_contracts_wsMessages_models_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_contracts_wsMessages_models_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_contracts_wsMessages_models_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contracts_wsMessages_models_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_wsMessages_models_proto_goTypes,
		DependencyIndexes: file_contracts_wsMessages_models_proto_depIdxs,
		EnumInfos:         file_contracts_wsMessages_models_proto_enumTypes,
		MessageInfos:      file_contracts_wsMessages_models_proto_msgTypes,
	}.Build()
	File_contracts_wsMessages_models_proto = out.File
	file_contracts_wsMessages_models_proto_rawDesc = nil
	file_contracts_wsMessages_models_proto_goTypes = nil
	file_contracts_wsMessages_models_proto_depIdxs = nil
}
