// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: wsMessages.proto

package wsMessages

import (
	_ "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutBoundMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*OutBoundMessage_SendMessage
	//	*OutBoundMessage_JoinChannel
	Message isOutBoundMessage_Message `protobuf_oneof:"message"`
}

func (x *OutBoundMessage) Reset() {
	*x = OutBoundMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wsMessages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutBoundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutBoundMessage) ProtoMessage() {}

func (x *OutBoundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_wsMessages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutBoundMessage.ProtoReflect.Descriptor instead.
func (*OutBoundMessage) Descriptor() ([]byte, []int) {
	return file_wsMessages_proto_rawDescGZIP(), []int{0}
}

func (m *OutBoundMessage) GetMessage() isOutBoundMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *OutBoundMessage) GetSendMessage() *SendMessage {
	if x, ok := x.GetMessage().(*OutBoundMessage_SendMessage); ok {
		return x.SendMessage
	}
	return nil
}

func (x *OutBoundMessage) GetJoinChannel() *JoinChannel {
	if x, ok := x.GetMessage().(*OutBoundMessage_JoinChannel); ok {
		return x.JoinChannel
	}
	return nil
}

type isOutBoundMessage_Message interface {
	isOutBoundMessage_Message()
}

type OutBoundMessage_SendMessage struct {
	// send new message to channel
	SendMessage *SendMessage `protobuf:"bytes,1,opt,name=sendMessage,proto3,oneof"`
}

type OutBoundMessage_JoinChannel struct {
	JoinChannel *JoinChannel `protobuf:"bytes,2,opt,name=joinChannel,proto3,oneof"`
}

func (*OutBoundMessage_SendMessage) isOutBoundMessage_Message() {}

func (*OutBoundMessage_JoinChannel) isOutBoundMessage_Message() {}

type InBoundMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*InBoundMessage_NewMessage
	//	*InBoundMessage_MeJoinedToChannel
	Message isInBoundMessage_Message `protobuf_oneof:"message"`
}

func (x *InBoundMessage) Reset() {
	*x = InBoundMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wsMessages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InBoundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InBoundMessage) ProtoMessage() {}

func (x *InBoundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_wsMessages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InBoundMessage.ProtoReflect.Descriptor instead.
func (*InBoundMessage) Descriptor() ([]byte, []int) {
	return file_wsMessages_proto_rawDescGZIP(), []int{1}
}

func (m *InBoundMessage) GetMessage() isInBoundMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *InBoundMessage) GetNewMessage() *Message {
	if x, ok := x.GetMessage().(*InBoundMessage_NewMessage); ok {
		return x.NewMessage
	}
	return nil
}

func (x *InBoundMessage) GetMeJoinedToChannel() *MeJoinedToChannel {
	if x, ok := x.GetMessage().(*InBoundMessage_MeJoinedToChannel); ok {
		return x.MeJoinedToChannel
	}
	return nil
}

type isInBoundMessage_Message interface {
	isInBoundMessage_Message()
}

type InBoundMessage_NewMessage struct {
	// sent when new message in chat received
	NewMessage *Message `protobuf:"bytes,1,opt,name=newMessage,proto3,oneof"`
}

type InBoundMessage_MeJoinedToChannel struct {
	MeJoinedToChannel *MeJoinedToChannel `protobuf:"bytes,2,opt,name=meJoinedToChannel,proto3,oneof"`
}

func (*InBoundMessage_NewMessage) isInBoundMessage_Message() {}

func (*InBoundMessage_MeJoinedToChannel) isInBoundMessage_Message() {}

type SendMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text       string      `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	LocalId    string      `protobuf:"bytes,2,opt,name=localId,proto3" json:"localId,omitempty"`
	CustomData *CustomData `protobuf:"bytes,3,opt,name=customData,proto3,oneof" json:"customData,omitempty"`
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wsMessages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_wsMessages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_wsMessages_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessage) GetLocalId() string {
	if x != nil {
		return x.LocalId
	}
	return ""
}

func (x *SendMessage) GetCustomData() *CustomData {
	if x != nil {
		return x.CustomData
	}
	return nil
}

type JoinChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InitialPageSize int64 `protobuf:"varint,1,opt,name=initialPageSize,proto3" json:"initialPageSize,omitempty"`
	InitialOffset   int64 `protobuf:"varint,2,opt,name=initialOffset,proto3" json:"initialOffset,omitempty"`
}

func (x *JoinChannel) Reset() {
	*x = JoinChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wsMessages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChannel) ProtoMessage() {}

func (x *JoinChannel) ProtoReflect() protoreflect.Message {
	mi := &file_wsMessages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChannel.ProtoReflect.Descriptor instead.
func (*JoinChannel) Descriptor() ([]byte, []int) {
	return file_wsMessages_proto_rawDescGZIP(), []int{3}
}

func (x *JoinChannel) GetInitialPageSize() int64 {
	if x != nil {
		return x.InitialPageSize
	}
	return 0
}

func (x *JoinChannel) GetInitialOffset() int64 {
	if x != nil {
		return x.InitialOffset
	}
	return 0
}

type ChannelInitialInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId       string     `protobuf:"bytes,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	HistoryMessages []*Message `protobuf:"bytes,2,rep,name=historyMessages,proto3" json:"historyMessages,omitempty"`
}

func (x *ChannelInitialInfo) Reset() {
	*x = ChannelInitialInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wsMessages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelInitialInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInitialInfo) ProtoMessage() {}

func (x *ChannelInitialInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wsMessages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInitialInfo.ProtoReflect.Descriptor instead.
func (*ChannelInitialInfo) Descriptor() ([]byte, []int) {
	return file_wsMessages_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelInitialInfo) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelInitialInfo) GetHistoryMessages() []*Message {
	if x != nil {
		return x.HistoryMessages
	}
	return nil
}

type MeJoinedToChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeIdentifier string              `protobuf:"bytes,1,opt,name=meIdentifier,proto3" json:"meIdentifier,omitempty"`
	IsSuccess    bool                `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	Channel      *ChannelInitialInfo `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *MeJoinedToChannel) Reset() {
	*x = MeJoinedToChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wsMessages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeJoinedToChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeJoinedToChannel) ProtoMessage() {}

func (x *MeJoinedToChannel) ProtoReflect() protoreflect.Message {
	mi := &file_wsMessages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeJoinedToChannel.ProtoReflect.Descriptor instead.
func (*MeJoinedToChannel) Descriptor() ([]byte, []int) {
	return file_wsMessages_proto_rawDescGZIP(), []int{5}
}

func (x *MeJoinedToChannel) GetMeIdentifier() string {
	if x != nil {
		return x.MeIdentifier
	}
	return ""
}

func (x *MeJoinedToChannel) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *MeJoinedToChannel) GetChannel() *ChannelInitialInfo {
	if x != nil {
		return x.Channel
	}
	return nil
}

var File_wsMessages_proto protoreflect.FileDescriptor

var file_wsMessages_proto_rawDesc = []byte{
	0x0a, 0x10, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x01,
	0x0a, 0x0f, 0x4f, 0x75, 0x74, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x00, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3b,
	0x0a, 0x0b, 0x6a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x0b,
	0x6a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x42, 0x09, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x42, 0x6f, 0x75,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x6e, 0x65, 0x77,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x4d, 0x0a, 0x11, 0x6d, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x54, 0x6f, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77, 0x73,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x65,
	0x64, 0x54, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x11, 0x6d, 0x65,
	0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x54, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x42,
	0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x0b, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x77,
	0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x5d, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x50, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x22, 0x71, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0f, 0x68, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x11, 0x4d, 0x65, 0x4a, 0x6f, 0x69,
	0x6e, 0x65, 0x64, 0x54, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x22, 0x0a, 0x0c,
	0x6d, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x38,
	0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x42, 0x16, 0x5a, 0x14, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x77, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wsMessages_proto_rawDescOnce sync.Once
	file_wsMessages_proto_rawDescData = file_wsMessages_proto_rawDesc
)

func file_wsMessages_proto_rawDescGZIP() []byte {
	file_wsMessages_proto_rawDescOnce.Do(func() {
		file_wsMessages_proto_rawDescData = protoimpl.X.CompressGZIP(file_wsMessages_proto_rawDescData)
	})
	return file_wsMessages_proto_rawDescData
}

var file_wsMessages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wsMessages_proto_goTypes = []interface{}{
	(*OutBoundMessage)(nil),    // 0: wsMessages.OutBoundMessage
	(*InBoundMessage)(nil),     // 1: wsMessages.InBoundMessage
	(*SendMessage)(nil),        // 2: wsMessages.SendMessage
	(*JoinChannel)(nil),        // 3: wsMessages.JoinChannel
	(*ChannelInitialInfo)(nil), // 4: wsMessages.ChannelInitialInfo
	(*MeJoinedToChannel)(nil),  // 5: wsMessages.MeJoinedToChannel
	(*Message)(nil),            // 6: wsMessages.Message
	(*CustomData)(nil),         // 7: wsMessages.CustomData
}
var file_wsMessages_proto_depIdxs = []int32{
	2, // 0: wsMessages.OutBoundMessage.sendMessage:type_name -> wsMessages.SendMessage
	3, // 1: wsMessages.OutBoundMessage.joinChannel:type_name -> wsMessages.JoinChannel
	6, // 2: wsMessages.InBoundMessage.newMessage:type_name -> wsMessages.Message
	5, // 3: wsMessages.InBoundMessage.meJoinedToChannel:type_name -> wsMessages.MeJoinedToChannel
	7, // 4: wsMessages.SendMessage.customData:type_name -> wsMessages.CustomData
	6, // 5: wsMessages.ChannelInitialInfo.historyMessages:type_name -> wsMessages.Message
	4, // 6: wsMessages.MeJoinedToChannel.channel:type_name -> wsMessages.ChannelInitialInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_wsMessages_proto_init() }
func file_wsMessages_proto_init() {
	if File_wsMessages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wsMessages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutBoundMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wsMessages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InBoundMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wsMessages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wsMessages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wsMessages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelInitialInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wsMessages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeJoinedToChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_wsMessages_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*OutBoundMessage_SendMessage)(nil),
		(*OutBoundMessage_JoinChannel)(nil),
	}
	file_wsMessages_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*InBoundMessage_NewMessage)(nil),
		(*InBoundMessage_MeJoinedToChannel)(nil),
	}
	file_wsMessages_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wsMessages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wsMessages_proto_goTypes,
		DependencyIndexes: file_wsMessages_proto_depIdxs,
		MessageInfos:      file_wsMessages_proto_msgTypes,
	}.Build()
	File_wsMessages_proto = out.File
	file_wsMessages_proto_rawDesc = nil
	file_wsMessages_proto_goTypes = nil
	file_wsMessages_proto_depIdxs = nil
}
